name: Build and Deploy on VPS

# This workflow runs only when you push a tag like v1.0.1, v1.2.0, etc.
on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This step securely connects to your VPS and runs the deployment script.
      # It no longer builds an image here. It tells the VPS to do it.
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Navigate to your app directory on the VPS
            cd /home/rafid/dummy-repo

            # Pull the latest changes from the main branch of your repository
            git pull origin main

            # IMPORTANT: Ensure the new tag is fetched
            git fetch --tags

            # Check out the specific tag that triggered this workflow
            # This ensures the version in package.json is correct for the build
            git checkout ${{ github.ref_name }}

            # Build and start the new container in the background
            docker compose up -d --build --force-recreate
            
            # --- SAFER DEPLOYMENT HEALTH CHECK ---
            echo "Waiting for application to start..."
            sleep 10 # Give the container a few seconds to initialize
            
            # Check if the application is responding correctly
            # The --fail flag makes curl exit with an error if the HTTP request fails
            if ! curl --fail http://localhost:8080; then
              echo "Health check failed! Application might be down."
              # Show the logs of the failed container for debugging
              docker compose logs
              # Exit with an error code to stop the workflow here
              exit 1
            fi
            
            echo "Health check passed! Deployment is successful."
            # --- END OF HEALTH CHECK ---
            
            # This line will only run if the health check above succeeds
            docker image prune -af

